// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZwzbMqd8BFpTfCZRgDLNs4zmTm9Vk7I',
    appId: '1:1091752419535:web:91dd2956d6e068b01717ba',
    messagingSenderId: '1091752419535',
    projectId: 'monitoringflutter',
    authDomain: 'monitoringflutter.firebaseapp.com',
    databaseURL: 'https://monitoringflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoringflutter.appspot.com',
    measurementId: 'G-9ZE5WPTBVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsflPYL7AFSglsCmw6GtP9OQVf0151UME',
    appId: '1:1091752419535:android:0402f2dda31168db1717ba',
    messagingSenderId: '1091752419535',
    projectId: 'monitoringflutter',
    databaseURL: 'https://monitoringflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoringflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1AAprgz_N2VMk_Sj0FZ0MlGJdxqC0ZMA',
    appId: '1:1091752419535:ios:837318ee490f3c2f1717ba',
    messagingSenderId: '1091752419535',
    projectId: 'monitoringflutter',
    databaseURL: 'https://monitoringflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoringflutter.appspot.com',
    iosBundleId: 'com.example.monitoringapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1AAprgz_N2VMk_Sj0FZ0MlGJdxqC0ZMA',
    appId: '1:1091752419535:ios:e8a9ce4664169caf1717ba',
    messagingSenderId: '1091752419535',
    projectId: 'monitoringflutter',
    databaseURL: 'https://monitoringflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitoringflutter.appspot.com',
    iosBundleId: 'com.example.monitoringapp.RunnerTests',
  );
}
