// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSvXbhXD6N_Rv62zI6zUrxCcR3WOS4G8',
    appId: '1:133746542095:web:afe63e165711c2faf0857a',
    messagingSenderId: '133746542095',
    projectId: 'akuaponikk',
    authDomain: 'akuaponikk.firebaseapp.com',
    databaseURL: 'https://akuaponikk-default-rtdb.firebaseio.com',
    storageBucket: 'akuaponikk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfc1YHcsAp2EhFGsQje7IwNfW-1LOJS0',
    appId: '1:133746542095:android:59b7f67d270403bcf0857a',
    messagingSenderId: '133746542095',
    projectId: 'akuaponikk',
    databaseURL: 'https://akuaponikk-default-rtdb.firebaseio.com',
    storageBucket: 'akuaponikk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3CSMtE_n_dvutpFmQMS_k1nIN2IJCRo',
    appId: '1:133746542095:ios:97e965ec52ce4f7ef0857a',
    messagingSenderId: '133746542095',
    projectId: 'akuaponikk',
    databaseURL: 'https://akuaponikk-default-rtdb.firebaseio.com',
    storageBucket: 'akuaponikk.appspot.com',
    iosBundleId: 'com.example.monitoringapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3CSMtE_n_dvutpFmQMS_k1nIN2IJCRo',
    appId: '1:133746542095:ios:0650eb81f32dcc4bf0857a',
    messagingSenderId: '133746542095',
    projectId: 'akuaponikk',
    databaseURL: 'https://akuaponikk-default-rtdb.firebaseio.com',
    storageBucket: 'akuaponikk.appspot.com',
    iosBundleId: 'com.example.monitoringapp.RunnerTests',
  );
}
